# Generated by Django 3.1.7 on 2021-03-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.IntegerField(db_index=True)),
                ('ticker_name', models.CharField(db_index=True, max_length=10)),
                ('avg_buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'ordering': ['portfolio_id'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('portfolio_id', models.IntegerField()),
                ('ticker_name', models.CharField(max_length=10)),
                ('trade_type', models.CharField(max_length=1)),
                ('trade_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trade_quantity', models.IntegerField()),
            ],
            options={
                'ordering': ['trade_id'],
            },
        ),
    ]
